import { precacheAndRoute, matchPrecache } from 'workbox-precaching';
import { Route, registerRoute, setDefaultHandler, setCatchHandler } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Inject precache manifest generated by Vite PWA
precacheAndRoute(self.__WB_MANIFEST);

// Handle HTML documents (that aren't already precached)
const contentRoute = new Route(({ request }) => {
  return request.destination === 'document';
}, new StaleWhileRevalidate({
  cacheName: 'content',
  plugins: [
    new ExpirationPlugin({
      maxAgeSeconds: 120 * 24 * 60 * 60,
      purgeOnQuotaError: true,
    }),
  ],
}));

// Handle images
const imageRoute = new Route(({ request }) => {
  return request.destination === 'image';
}, new CacheFirst({
  cacheName: 'images',
  plugins: [
    new ExpirationPlugin({
      maxAgeSeconds: 120 * 24 * 60 * 60,
      purgeOnQuotaError: true,
    }),
  ],
}));

// Handle scripts
const scriptsRoute = new Route(({ request }) => {
  return request.destination === 'script';
}, new CacheFirst({
  cacheName: 'scripts',
  plugins: [
    new ExpirationPlugin({
      maxAgeSeconds: 30 * 24 * 60 * 60,
      maxEntries: 30,
      purgeOnQuotaError: true,
    }),
    new CacheableResponsePlugin({
      statuses: [0, 200],
    }),
  ],
}));

// Handle styles
const stylesRoute = new Route(({ request }) => {
  return request.destination === 'style';
}, new CacheFirst({
  cacheName: 'styles',
  plugins: [
    new ExpirationPlugin({
      maxAgeSeconds: 30 * 24 * 60 * 60,
      maxEntries: 30,
      purgeOnQuotaError: true,
    }),
    new CacheableResponsePlugin({
      statuses: [0, 200],
    }),
  ],
}));

// Handle fonts
const fontRoute = new Route(({ request }) => {
  return request.destination === 'font';
}, new StaleWhileRevalidate({
  cacheName: 'fonts',
  plugins: [
    new ExpirationPlugin({
      maxAgeSeconds: 120 * 24 * 60 * 60,
      purgeOnQuotaError: true,
    }),
    new CacheableResponsePlugin({
      statuses: [0, 200],
    }),
  ],
}));

// Register runtime routes
registerRoute(contentRoute);
registerRoute(imageRoute);
registerRoute(scriptsRoute);
registerRoute(stylesRoute);
registerRoute(fontRoute);

// Set default caching strategy for any unmatched routes
setDefaultHandler(new StaleWhileRevalidate());

// Global fallback handler for routing failures
setCatchHandler(async ({ event }) => {
  switch (event.request.destination) {
    case 'document':
      try {
        // Check if the user manually saved this post for offline reading
        const customCache = await caches.match(event.request, { cacheName: 'offline-saved-posts' });
        if (customCache) return customCache;
      } catch (e) {}
      
      // Updated to match Astro's directory output format
      return matchPrecache('offline/index.html');

    case 'image':
      try {
        // Check if the image was manually saved alongside an offline post
        const customImg = await caches.match(event.request, { cacheName: 'offline-saved-posts' });
        if (customImg) return customImg;
      } catch (e) {}
      
      // SVG minified to a single line prevents the workbox parser from breaking
      return new Response(
        '<svg role="img" aria-labelledby="offline-title" viewBox="0 0 400 300" xmlns="http://www.w3.org/2000/svg"><title id="offline-title">Offline</title><g fill="none" fill-rule="evenodd"><path fill="#D8D8D8" d="M0 0h400v300H0z"></path><text fill="#9B9B9B" font-family="Helvetica Neue,Arial,Helvetica,sans-serif" font-size="72" font-weight="bold"><tspan x="93" y="172">offline</tspan></text></g></svg>',
        {
          headers: {
            'Content-Type': 'image/svg+xml',
            'Cache-Control': 'no-store',
          },
        }
      );

    default:
      return Response.error();
  }
});

// Allow the React component to trigger skipWaiting to update the SW
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
